# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/api_monitor
spring.datasource.username=monitor_user
spring.datasource.password=monitor_pass123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# App
spring.application.name=pinger